### ISSUE TITLE
Cancel request feature

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/ids.server#41] opened 2016-02-04 15:24 UTC
It should be possible to issue a pause and/or cancel call on a prepare request.

**Comment by tomgriffinstfc** [comment] 2016-02-04 15:24
https://github.com/icatproject/topcat/issues/152

**Comment by fisherab** [comment] 2016-02-04 16:38
Pausing a prepare request is meaningless. All that cancelling could do would be to delete the preparedId so that it could no longer be referenced.

**Comment by tomgriffinstfc** [comment] 2016-02-05 09:15
This is an issue in certain two-layer storage systems where there is a problem in the underlying tape system. The IDS current repeatedly resubmits the request if problems occur. The (admin) user should be able to calcel the request to stop further repeat submits in the case of a major problem (missing files etc) and pause (and restart) requests in the case of temporary issues, such as tape drive failure.

**Comment by fisherab** [comment] 2016-02-05 10:13
I'm happy with this as an administration operation as it avoids having the
IDS loop for ever.

**Comment by fisherab** [comment] 2016-03-01 11:57
Will treat this as a duplicate of #33

**Closed** 2016-03-01 11:59 UTC
Labels: duplicate, enhancement
